/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aritmatika;

/**
 *
 * @author AbayPC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPenjumlahan = new javax.swing.JButton();
        btnPengurangan = new javax.swing.JButton();
        btnPembagian = new javax.swing.JButton();
        btnPangkat = new javax.swing.JButton();
        btnDeret = new javax.swing.JButton();
        btnPerkalian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Aritmatika");

        btnPenjumlahan.setText("Penjumlahan");
        btnPenjumlahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjumlahanActionPerformed(evt);
            }
        });

        btnPengurangan.setText("Pengurangan");
        btnPengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenguranganActionPerformed(evt);
            }
        });

        btnPembagian.setText("Pembagian");
        btnPembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembagianActionPerformed(evt);
            }
        });

        btnPangkat.setText("Pangkat");
        btnPangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPangkatActionPerformed(evt);
            }
        });

        btnDeret.setText("Fungsi");
        btnDeret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeretActionPerformed(evt);
            }
        });

        btnPerkalian.setText("Perkalian");
        btnPerkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerkalianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPenjumlahan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeret, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPerkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnPenjumlahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPengurangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPembagian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPerkalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPangkat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeret)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPenjumlahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjumlahanActionPerformed
        Penjumlahan a = new Penjumlahan();
        a.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnPenjumlahanActionPerformed

    private void btnPenguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenguranganActionPerformed
        Pengurangan b = new Pengurangan();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPenguranganActionPerformed

    private void btnPembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembagianActionPerformed
        Pembagian c = new Pembagian();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPembagianActionPerformed

    private void btnPangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPangkatActionPerformed
        Pangkat d = new Pangkat();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPangkatActionPerformed

    private void btnPerkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerkalianActionPerformed
        Perkalian e = new Perkalian();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPerkalianActionPerformed

    private void btnDeretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeretActionPerformed
        Fungsi f = new Fungsi();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeretActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeret;
    private javax.swing.JButton btnPangkat;
    private javax.swing.JButton btnPembagian;
    private javax.swing.JButton btnPengurangan;
    private javax.swing.JButton btnPenjumlahan;
    private javax.swing.JButton btnPerkalian;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
